#!/bin/bash
# Quick Start - Google Drive Sync for Shop Manager

echo "=========================================="
echo "Shop Manager - Google Drive Sync"
echo "Quick Start Guide"
echo "=========================================="
echo ""

echo "📧 EMAIL-TO-WEBSITE AUTOMATION"
echo ""
echo "You email → Gmail → Google Drive → Server → Website"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if services are already installed
if [ -f "/etc/systemd/system/shopmgr-gdrive-sync.service" ]; then
    echo "✓ Services are already installed"
    echo ""
    echo "Current status:"
    sudo systemctl status shopmgr-gdrive-sync --no-pager | grep "Active:"
    sudo systemctl status shopmgr-file-watcher --no-pager | grep "Active:"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Commands:"
    echo "  Start:   sudo systemctl start shopmgr-gdrive-sync"
    echo "  Stop:    sudo systemctl stop shopmgr-gdrive-sync"
    echo "  Status:  sudo systemctl status shopmgr-gdrive-sync"
    echo "  Logs:    tail -f ~/shopmgr/gdrive_sync.log"
    echo ""
else
    echo "⚙️  Services not yet installed"
    echo ""
    echo "To install:"
    echo "  sudo ./setup_gdrive_services.sh"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 DAILY USAGE (3 steps):"
echo ""
echo "  1. Create your report in Infinity"
echo "  2. Email to: jdean64@gmail.com"
echo "     Subject: shopmgr"
echo "     Attach your Excel file"
echo "  3. Done! Website updates in ~2 minutes"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 FIRST-TIME SETUP:"
echo ""
echo "  1. Gmail Filter Setup (one-time)"
echo "     • Go to Gmail settings"
echo "     • Create filter: subject='shopmgr' + has attachment"
echo "     • Action: Save to Google Drive /shopmgr folder"
echo "     (Use Gmail add-on or Zapier - see full guide)"
echo ""
echo "  2. Test Connection"
echo "     ./test_gdrive.sh"
echo ""
echo "  3. Install Services"
echo "     sudo ./setup_gdrive_services.sh"
echo ""
echo "  4. Start Services"
echo "     sudo systemctl start shopmgr-gdrive-sync"
echo "     sudo systemctl start shopmgr-file-watcher"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Documentation:"
echo "  Full Guide: cat GDRIVE_SETUP_GUIDE.md"
echo "  View Logs:  tail -f gdrive_sync.log"
echo ""
echo "🌐 Your Website:"
echo "  https://shop.coresteensma.com"
echo ""
